TITLE_1: PGF5001
TITLE_2: Mecânica Quântica
SUBTITLE_1: Disciplina de pós-graduação
SUBTITLE_2: Material de aula, notebooks e referências.

ABOUT: |
  Este site organiza as aulas, exercícios e material suplementar da disciplina.

REFERENCIAS: |
  <ul>
    <li>Livro AA …</li>
    <li>Artigo BB …</li>
  </ul>

GITHUB_LINK: https://github.com/Academic-Codex/PGF5001-Mecanica-Quantica

HERO_FILE: mecanica-quantica.png
